apiVersion: v1
# Not an actual instance of storage
# It will be attached to the pod so
# k8s can find the specified instance of storage
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
